version: '3.7'

networks:
  appnet:
    external: true
    
services:
  broker:
    image: rabbitmq:latest
    deploy:
       replicas: 1
       placement:
        constraints: [node.role == worker]
    ports:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: mayan
      RABBITMQ_DEFAULT_PASS: mayan
      RABBITMQ_DEFAULT_VHOST: mayan
    volumes:
    - broker:/var/lib/rabbitmq
    networks:
      - appnet
    
  results:
    image: redis:latest
    deploy:
       replicas: 1
       placement:
        constraints: [node.role == worker]
    volumes:
      - results:/data
    networks:
      - appnet
      
  db:
    image: postgres:9.5
    deploy:
       replicas: 1
       placement:
        constraints: [node.role == worker]
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayanpassword
      POSTGRES_USER: mayan
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet
      
  mayan-edms:
    image: mayanedms/mayanedms:latest
    user: 0:0
    deploy:
       replicas: 1
       placement:
        constraints: [node.role == worker]
    depends_on:
      - broker
      - db
      - results
    environment:
      MAYAN_BROKER_URL: amqp://mayan:mayan@broker:5672/mayan
      MAYAN_CELERY_RESULT_BACKEND: redis://results:6379/0
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: db
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayanpassword
      MAYAN_DATABASE_USER: mayan
    ports:
      - "8887:8000"
    volumes:
      - app:/var/lib/mayan
    networks:
      - appnet
      
      
volumes:
   db:
     driver: local
     driver_opts:
       type: nfs
       o: addr=yournfshost.com,hard,nolock,rw
       device: ":/path/to/files"
       
   app:
     driver: local
     driver_opts:
       type: nfs
       o: addr=yournfshost.com,hard,nolock,rw
       device: ":/path/to/files"
        
   results:
     driver: local
     driver_opts:
       type: nfs
       o: addr=yournfshost.com,hard,nolock,rw
       device: ":/path/to/files"
    
   broker:
     driver: local
     driver_opts:
       type: nfs
       o: addr=yournfshost.com,hard,nolock,rw
       device: ":/path/to/files"
       
   nextcloud:
     driver: local
     driver_opts:
       type: nfs
       o: addr=yournfshost.com,hard,nolock,rw
       device: ":/path/to/files"
